// This file is generated by kconfig_compiler from KSGlobalConfig.kcfg.
// All changes you do to this file will be lost.

#include "KSGlobalConfig.h"

using namespace kscope4;

KSGlobalConfig::KSGlobalConfig(  )
  : KConfigSkeleton( QLatin1String( "KSGlobalConfig" ) )
{
  setCurrentGroup( QLatin1String( "Projects" ) );

  KConfigSkeleton::ItemStringList  *itemRecentProjects;
  itemRecentProjects = new KConfigSkeleton::ItemStringList( currentGroup(), QLatin1String( "RecentProjects" ), mRecentProjects );
  addItem( itemRecentProjects, QLatin1String( "RecentProjects" ) );
}

KSGlobalConfig::~KSGlobalConfig()
{
}

