// This file is generated by kconfig_compiler from KSGlobalConfig.kcfg.
// All changes you do to this file will be lost.

#include "KSGlobalConfig.h"

using namespace kscope4;

KSGlobalConfig::KSGlobalConfig(  )
  : KConfigSkeleton( QLatin1String( "KSGlobalConfig" ) )
{
  setCurrentGroup( QLatin1String( "Projects" ) );

  KConfigSkeleton::ItemStringList  *itemRecentProjects;
  itemRecentProjects = new KConfigSkeleton::ItemStringList( currentGroup(), QLatin1String( "RecentProjects" ), mRecentProjects );
  addItem( itemRecentProjects, QLatin1String( "RecentProjects" ) );
  KConfigSkeleton::ItemString  *itemLastOpenProject;
  itemLastOpenProject = new KConfigSkeleton::ItemString( currentGroup(), QLatin1String( "LastOpenProject" ), mLastOpenProject );
  addItem( itemLastOpenProject, QLatin1String( "LastOpenProject" ) );
  KConfigSkeleton::ItemInt  *itemVcs;
  itemVcs = new KConfigSkeleton::ItemInt( currentGroup(), QLatin1String( "vcs" ), mVcs );
  addItem( itemVcs, QLatin1String( "vcs" ) );
  KConfigSkeleton::ItemStringList  *itemOpenedFiles;
  itemOpenedFiles = new KConfigSkeleton::ItemStringList( currentGroup(), QLatin1String( "OpenedFiles" ), mOpenedFiles );
  addItem( itemOpenedFiles, QLatin1String( "OpenedFiles" ) );
}

KSGlobalConfig::~KSGlobalConfig()
{
}

