// This file is generated by kconfig_compiler from KSGlobalConfig.kcfg.
// All changes you do to this file will be lost.
#ifndef KSCOPE4_KSGLOBALCONFIG_H
#define KSCOPE4_KSGLOBALCONFIG_H

#include <kglobal.h>
#include <kconfigskeleton.h>
#include <kdebug.h>

#include <kglobalsettings.h>
namespace kscope4 {

class KSGlobalConfig : public KConfigSkeleton
{
  public:

    KSGlobalConfig( );
    ~KSGlobalConfig();


    /**
      Get List of recent projects
    */
    QStringList recentProjects() const
    {
      return mRecentProjects;
    }


    /**
      Get Path to the last open project
    */
    QString lastOpenProject() const
    {
      return mLastOpenProject;
    }


    /**
      Get Which Version Control System is Used
    */
    int vcs() const
    {
      return mVcs;
    }


    /**
      Get List of Files Which Were Still Open When We Closed
    */
    QStringList openedFiles() const
    {
      return mOpenedFiles;
    }

  protected:

    // Projects
    QStringList mRecentProjects;
    QString mLastOpenProject;
    int mVcs;
    QStringList mOpenedFiles;

  private:
};

}

#endif

